### ISSUE TITLE
tips to get carnet working in osx mac?

### ISSUE THREAD

**Issue by muranava** [CarnetApp/CarnetElectron#37]
Hi apologies if this not best place to ask this question,
How can I get carnet working on apple osx?
After following default install commands (using homebrew then npm) when I launch HTML file I get circular loading icon?
Thanks

**Comment by PhieF** [comment]
Now mac OS has an official release

See here

https://github.com/CarnetApp/CarnetDocumentation

**Comment by muranava** [comment]
sweet gonna test it now!

    On Saturday, 23 May 2020, 16:05:09 CEST, PhieF <notifications@github.com> wrote:  
 
 


Now mac OS has an official release

See here

https://github.com/CarnetApp/CarnetDocumentation
