### ISSUE TITLE
Java error adding a picture (x64 Appimage)

### ISSUE THREAD

**Issue by bipox** [CarnetApp/CarnetElectron#38]
I couldn't copy and paste the error message, so I made a [screenshot](https://ncloud.zaclys.com/index.php/s/8fWfodWXScA6yFn/preview)

In the message it says *thepicturename*.png.jpg
But the picture is .png on my computer

On KDE Neon.

I really like where the app is going, keep up the good work!

**Comment by PhieF** [comment]
It doesn't seem to happen anymore ? Can you recheck if you are still using it after all this time ?

Thank you and sorry for the time it took, I'm closing it for now, feel free to reopen the issue :)
