### ISSUE TITLE
Ubuntu Snap Carnet - Google Keep Import - Where to put files?

### ISSUE THREAD

**Issue by qwertyuser1983** [CarnetApp/CarnetElectron#39]
I have extracted the imported folder somewhere in my home, but, 

The import windows just spinning around. 

(｡•́︿•̀｡) 

Carnet App https://snapcraft.io/carnet
Carnet Server in Nextcloud Snap https://snapcraft.io/nextcloud

**Comment by PhieF** [comment]
I'm closing this since I've reworked the importer, you can always reopen in case of need !

**Comment by mind-overflow** [comment]
The import feature does not work. I download the archive from Google Takeout, select it in Carnet, and this is the result:

![Schermata da 2020-08-15 00-23-26](https://user-images.githubusercontent.com/67104846/90297080-ae0c0600-de8d-11ea-93fd-6d3ba2a4fe82.png)

**Comment by wizpig** [comment]
> The import feature does not work. I download the archive from Google Takeout, select it in Carnet, and this is the result:
> 
> ![Schermata da 2020-08-15 00-23-26](https://user-images.githubusercontent.com/67104846/90297080-ae0c0600-de8d-11ea-93fd-6d3ba2a4fe82.png)

This still seems to be the case. I have the exact same issue. Had someone success with importing?

**Comment by AlexDerk** [comment]
> > The import feature does not work. I download the archive from Google Takeout, select it in Carnet, and this is the result:
> > ![Schermata da 2020-08-15 00-23-26](https://user-images.githubusercontent.com/67104846/90297080-ae0c0600-de8d-11ea-93fd-6d3ba2a4fe82.png)
> 
> This still seems to be the case. I have the exact same issue. Had someone success with importing?

OK, I got it after checking the source code of the importer!

The solution is:

The importer expects the folder structure in your Takeout zip-file to be "Takeout/Keep".
However depending on your language settings at Google the second folder may have a different name. E.g. for German it is named "Google Notizen". The most naive solution is therefore to unzip the file, change the name of the second folder to "Keep" and to zip everything again. 
The import works now for me.
