### ISSUE TITLE
Update Snap

### ISSUE THREAD

**Issue by digitalethics** [CarnetApp/CarnetElectron#40]
Could you update your app on the Snapcraft Store? I just downloaded it and it immediately prompts to download a newer version which doesn't exist. It only points to the AppImage. I'd rather avoid AppImages because they don't have any form of sandboxing and no auto-update functionality.

**Comment by PhieF** [comment]
Hi, is it ok now ? 

Thanks !

**Comment by digitalethics** [comment]
Thanks, this is fixed now.
