### ISSUE TITLE
Catalina (10.15.4) Problem 

### ISSUE THREAD

**Issue by mtashackori** [CarnetApp/CarnetElectron#41]
a problem for running macosx client, on Catalina (10.15.4)

cannot open file!

**Comment by PhieF** [comment]
I've just tried on mac os cataline with this build
https://qn.phie.ovh/binaries/desktop/currentMac.zip
It automatically extract the app file, when running it it warns you that the app isn't trusted
You need to hit the apple button on the top left, then go in system settings, security, and find "open anyway"
![Capture d’écran de 2020-05-22 18-40-16](https://user-images.githubusercontent.com/26841885/82689998-b6242300-9c5b-11ea-89df-1850d0fdea14.png)

**Comment by mtashackori** [comment]
<img width="424" alt="Screen Shot 1399-03-02 at 9 27 57 عصر" src="https://user-images.githubusercontent.com/16570244/82691480-3ace6b80-9c73-11ea-876a-1a9a57332c18.png">
This error is mine!

**Comment by PhieF** [comment]
Ok !

Can you try this version ?

https://qn.phie.ovh/binaries/desktop/currentMac.dmg

**Comment by mtashackori** [comment]
Solved!
Runs properly and I'm using it.
Thanks a lot

**Comment by PhieF** [comment]
Thanks for your report !
